name: Publish to Docker Hub

on:
  push:
    branches:
    - 'master'

jobs:
  docker:
    strategy:
      matrix:
        image:
        - postfix
        - dovecot
        - opendkim
        - rainloop
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:${{ matrix.image }}"
        push: true
        tags: ${{ github.repository_owner }}/${{ matrix.image }}:${{ github.ref_name }}
